//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public string DietaryRequirements { get; set; }
        public string SongRequest { get; set; }
        public int RsvpStatusId { get; set; }
        public System.Guid HouseholdId { get; set; }
        public bool IsChild { get; set; }
        public int HotelRequirementId { get; set; }
        public bool RequiresTransport { get; set; }
    
        public virtual Household Household { get; set; }
        public virtual RsvpStatus RsvpStatus { get; set; }
    }
}
